### ISSUE TITLE
what is _sigalrm_handler?

### ISSUE THREAD

**Issue by mu-777** [kyoto-u-shinobi/yozakura#31]
https://github.com/kyoto-u-shinobi/yozakura/blob/develop/opstn/server.py#L84

**Comment by masasin** [comment]
A `SIGALRM` is a signal from the Linux Kernel which we set up every time we try and receive UDP. 

The Linux `alarm` function only works with an integer number of seconds, so we use `setitimer` instead. This lets us have a much higher resolution.

`setitimer` is an iterative timer. It repeats over and over again, and sends a `SIGALRM` first at the delay, and then at whatever interval you set. (In this case, it's zero.)

When a signal arrives from the kernel, Linux checks to see if there is a handler for it. When we call `signal(SIGNAME, handler)` registers each signal to a handler. The handler here is on line 349, and it just returns a timeout error.

**Comment by mu-777** [comment]
sorry.
I was just wondering it because my pycharm alart me that there is no _sigalrm_handler at L84.
But I found out that _sigalrm_handler is defined in handler class and you just forgot to put self. before _sigalrm_handler.
Just I missed it.

thanks

**Comment by masasin** [comment]
My bad. All's good then. Thank you.
